# Intel XPU configuration for PD Disaggregation
# This configuration sets up prefill and decode services with Intel XPU optimization

multinode: false

# Configure accelerator type for Intel XPU
accelerator:
  type: intel

modelArtifacts:
  uri: "hf://deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"
  size: 10Gi  # Smaller model size for Intel XPU
  authSecretName: "llm-d-hf-token"
  name: "deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B"

routing:
  servicePort: 8000
  proxy:
    image: ghcr.io/llm-d/llm-d-routing-sidecar:v0.3.0
    connector: nixlv2
    secure: false

  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      # name: # set in helmfile

  inferencePool:
    create: false

  # create httpRoute via MS for using release name xpu-pd override
  httpRoute:
    create: true

  epp:
    create: false

decode:
  create: true
  replicas: 1
  monitoring:
    podmonitor:
      enabled: true
      portName: "metrics" # decode vLLM service port (from routing.proxy.targetPort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: ghcr.io/llm-d/llm-d-xpu-dev:pr-357
    modelCommand: vllmServe
    args:
      - "--block-size"
      - "128"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both", "kv_buffer_device":"cpu"}'
      - "--disable-log-requests"
      - "--disable-uvicorn-access-log"
      - "--max-model-len"
      - "32000"
    securityContext:
      fsGroup: 107
      supplementalGroups:
        - 107
    env:
      - name: UCX_TLS
        value: "tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
    ports:
      - containerPort: 8200
        name: metrics
        protocol: TCP
    resources:
      limits:
        memory: 64Gi
        cpu: "16"
        gpu.intel.com/i915: "1"
      requests:
        memory: 64Gi
        cpu: "16"
        gpu.intel.com/i915: "1"
    mountModelVolume: true
    volumeMounts:
      - name: dshm
        mountPath: /dev/shm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 4Gi

prefill:
  create: true
  replicas: 3
  monitoring:
    podmonitor:
      enabled: true
      portName: "metrics" # prefill vLLM service port (from routing.servicePort)
      path: "/metrics"
      interval: "30s"
  containers:
  - name: "vllm"
    image: ghcr.io/llm-d/llm-d-xpu-dev:pr-357
    modelCommand: vllmServe
    args:
      - "--block-size"
      - "128"
      - "--kv-transfer-config"
      - '{"kv_connector":"NixlConnector", "kv_role":"kv_both", "kv_buffer_device":"cpu"}'
      - "--disable-log-requests"
      - "--disable-uvicorn-access-log"
      - "--max-model-len"
      - "32000"
    securityContext:
      fsGroup: 107
      supplementalGroups:
        - 107
    env:
      - name: UCX_TLS
        value: "tcp"
      - name: VLLM_NIXL_SIDE_CHANNEL_HOST
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: VLLM_NIXL_SIDE_CHANNEL_PORT
        value: "5557"
    ports:
      - containerPort: 8000
        name: metrics
        protocol: TCP
    resources:
      limits:
        memory: 64Gi
        cpu: "8"
        gpu.intel.com/i915: "1"
      requests:
        memory: 64Gi
        cpu: "8"
        gpu.intel.com/i915: "1"
    mountModelVolume: true
    volumeMounts:
      - name: dshm
        mountPath: /dev/shm
  volumes:
    - name: dshm
      emptyDir:
        medium: Memory
        sizeLimit: 4Gi
