apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/volumes/0
        value: 
          name: weka-storage
          persistentVolumeClaim:
            claimName: wekafs-amg
