FROM vllm-cpu-base


# install pkg-config
RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

# copy install_nixl to /workspace folder 
COPY install_nixl.py /workspace/install_nixl.py

# install latest nixl with UCX package
RUN python /workspace/install_nixl.py 


# ENTRYPOINT
ENTRYPOINT ["/bin/bash"]

