FROM vllm-cpu-base


# 安装 pkg-config
RUN apt-get update && apt-get install -y --no-install-recommends \
    pkg-config \
 && rm -rf /var/lib/apt/lists/*

# 拷贝本地的安装脚本
COPY install_nixl.py /workspace/install_nixl.py

# 运行脚本安装 nixl==0.6.1
RUN python /workspace/install_nixl.py 


# 改变 ENTRYPOINT
ENTRYPOINT ["/bin/bash"]

