apiVersion: v1
kind: ConfigMap
metadata:
  name: infra-pd-inference-gateway
data:
  deployment: |
    spec:
      template:
        spec:
          containers:
          - name: istio-proxy
            args:
              - proxy
              - router
              - --domain
              - $(POD_NAMESPACE).svc.cluster.local
              - --proxyLogLevel
              - error
              - --proxyComponentLogLevel
              - misc:error
              - --log_output_level
              - default:error
            resources: 
              limits:
                cpu: "4"
                memory: 4Gi
              requests:
                cpu: "1"
                memory: 1Gi
  service: |
    spec:
      # -- Gateway's service type. Ingress is only available if the service type is set to LoadBalancer. Accepted values: ["LoadBalancer", "ClusterIP", "NodePort"]
      type: "LoadBalancer"
