apiVersion: leaderworkerset.x-k8s.io/v1
kind: LeaderWorkerSet
metadata:
  name: wide-ep-llm-d-prefill
  labels:
    llm-d.ai/inferenceServing: "true"
    llm-d.ai/model: DeepSeek-R1-0528
    llm-d.ai/role: prefill
spec:
  replicas: 1
  leaderWorkerTemplate:
    size: 4
    workerTemplate:
      metadata:
        labels:
          llm-d.ai/inferenceServing: "true"
          llm-d.ai/model: DeepSeek-R1-0528
          llm-d.ai/role: prefill
      spec:
        volumes:
          - name: dshm
            emptyDir:
              medium: Memory
              sizeLimit: 2Gi # 2Gi for NCCL 2.27 to be safe
          
        containers:
        - name: vllm-worker
          #image: ghcr.io/llm-d/llm-d-dev:pr-253@sha256:f6cbe2e42170abe0126e4c27a95b4828a4cf95856b5a8d6f6a6cb3c17c70be3b
          image: quay.io/tms/llm-d-dev:0.3.0-7c6404d3206a80734523f95d7e6a3c49687e1133
          securityContext:
            capabilities:
              add:
              - IPC_LOCK
              - SYS_RAWIO
            runAsGroup: 0
            runAsUser: 0
          imagePullPolicy: Always
          
          command:
            - /bin/bash
            - -c
          args:
            - |-
              #################
              # RUN vLLM prefill worker
              #################
              set -euo pipefail
              START_RANK=$(( ${LWS_WORKER_INDEX:-0} * DP_SIZE_LOCAL ))
              DP_SIZE=$(( ${LWS_GROUP_SIZE:-1} * DP_SIZE_LOCAL ))
            
              source /opt/vllm/bin/activate
              exec vllm serve \
                deepseek-ai/DeepSeek-R1-0528 \
                --port 8000 \
                --trust-remote-code \
                --disable-uvicorn-access-log \
                --enable-expert-parallel \
                --data-parallel-hybrid-lb \
                --tensor-parallel-size $TP_SIZE \
                --data-parallel-size $DP_SIZE \
                --data-parallel-size-local $DP_SIZE_LOCAL \
                --data-parallel-address ${LWS_LEADER_ADDRESS} \
                --data-parallel-rpc-port 5555 \
                --data-parallel-start-rank $START_RANK \
                --kv_transfer_config '{"kv_connector":"NixlConnector",
                                        "kv_role":"kv_both"}' \
                --enable-dbo \
                --dbo-decode-token-threshold 32
          env:
          - name: VLLM_CACHE_ROOT
            value: "/vllm-cache"

            # vLLM warms up DeepGEMM kernels to avoid high-variance slowdowns due to jitting.
            # Especially important for the prefill instances, affecting TTFT.
            # Safe to set once the DeepGEMM cache is on every node.
          #- name: VLLM_SKIP_DEEP_GEMM_WARMUP
          #  value: "1"

          - name: DP_SIZE_LOCAL
            value: "8"
          - name: TRITON_LIBCUDA_PATH
            value: /usr/lib64
          - name: HF_HUB_DISABLE_XET
            value: "1"
          - name: VLLM_SKIP_P2P_CHECK
            value: "1"
          - name: VLLM_RANDOMIZE_DP_DUMMY_INPUTS
            value: "1"
          - name: VLLM_USE_DEEP_GEMM
            value: "1"
          - name: VLLM_ALL2ALL_BACKEND
            value: deepep_high_throughput
          - name: NVIDIA_GDRCOPY
            value: enabled
          - name: NVSHMEM_DEBUG
            value: INFO
          - name: NVSHMEM_REMOTE_TRANSPORT
            value: ibgda
          - name: NVSHMEM_IB_ENABLE_IBGDA
            value: "true"
          - name: NVSHMEM_BOOTSTRAP_UID_SOCK_IFNAME
            value: eth0
          - name: GLOO_SOCKET_IFNAME
            value: eth0
          - name: NCCL_SOCKET_IFNAME
            value: eth0
          - name: NCCL_IB_HCA
            value: ibp
          - name: VLLM_LOGGING_LEVEL
            value: INFO
          - name: HF_HUB_CACHE
            value: /huggingface-cache
          - name: VLLM_NIXL_SIDE_CHANNEL_HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: TP_SIZE
            value: "1"
          ports:
          - containerPort: 8000
            name: metrics
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
          
          resources:
            limits:
              ephemeral-storage: 64Gi
              memory: 512Gi
              nvidia.com/gpu: "8"
            requests:
              cpu: 32
              ephemeral-storage: 64Gi
              memory: 512Gi
              nvidia.com/gpu: "8"
          
          volumeMounts:
            - name: dshm
              mountPath: /dev/shm
            - name: hf-cache
              mountPath: /huggingface-cache
            - name: vllm-cache
              mountPath: /vllm-cache
          workingDir: /code
