name: CI - PR Checks

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
      - dev

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck

      - name: Install hadolint
        run: |
          wget -O /usr/local/bin/hadolint \
            https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64
          chmod +x /usr/local/bin/hadolint
        shell: bash

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: warning about ignored paths
        run: |
          echo "Warning! Some paths are ignored in the markdown link checker config.
          This is because those websites have strong anti-scraping behaviours. For
          the full list of ignored paths, see the .markdownlinkcheck.json file:"
          cat .markdownlinkcheck.json

      - name: Run markdown link checker
        uses: ./.github/actions/markdown-link-checker
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
